# Generated by Django 2.1.7 on 2019-03-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyInfo',
            fields=[
                ('PharmacyID', models.CharField(max_length=200,
                                                primary_key=True,
                                                serialize=False)),
                ('PharmacyNumber', models.CharField(max_length=15)),
                ('PharmacyNPI', models.CharField(max_length=15)),
                ('PharmacyTaxId', models.CharField(max_length=15)),
                ('PharmacyName', models.CharField(max_length=200)),
                ('PharmacyStreetAddress1', models.CharField(max_length=200)),
                ('PharmacyCity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCodeInfo',
            fields=[
                ('zipcode', models.CharField(max_length=5, primary_key=True,
                                             serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='pharmacyinfo',
            name='PharmacyZip',
            field=models.ForeignKey(on_delete='set null',
                                    to='rx_info.ZipCodeInfo'),
        ),
    ]
