# Generated by Django 2.1.7 on 2019-03-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyinfo',
            name='PharmacyTaxId',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
