# Generated by Django 2.1.7 on 2019-03-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandToGeneric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=200)),
                ('Generic', models.CharField(max_length=200)),
            ],
        ),
    ]
