# Generated by Django 2.1.7 on 2019-03-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx_info', '0002_brandtogeneric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandtogeneric',
            name='Brand',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='brandtogeneric',
            name='Generic',
            field=models.CharField(max_length=500),
        ),
    ]
