# Generated by Django 2.1.7 on 2019-03-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx_info', '0003_auto_20190310_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandtogeneric',
            name='Brand',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='brandtogeneric',
            name='Generic',
            field=models.CharField(max_length=600),
        ),
    ]
