# Generated by Django 2.1.7 on 2019-03-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rx_info', '0004_auto_20190310_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='RxClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitCost', models.FloatField()),
                ('DrugLabelName', models.CharField(max_length=200)),
                ('PBMVendor', models.CharField(max_length=200)),
                ('PharmacyID', models.ForeignKey(on_delete='set null', to='rx_info.PharmacyInfo')),
            ],
        ),
    ]
