# Generated by Django 2.1.7 on 2019-03-11 05:16

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('rx_info', '0005_rxclaim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyinfo',
            name='PharmacyNPI',
        ),
        migrations.RemoveField(
            model_name='pharmacyinfo',
            name='PharmacyNumber',
        ),
        migrations.RemoveField(
            model_name='pharmacyinfo',
            name='PharmacyTaxId',
        ),
        migrations.AddField(
            model_name='pharmacyinfo',
            name='PharmacyNumbers',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
            preserve_default=False,
        ),
    ]
